import type { SubtitleStyle } from "./types";

export type SubtitleTemplate = {
  id: string;
  name: string;
  description: string;
  category: "viral" | "clean" | "fun" | "elegant";
  style: SubtitleStyle;
  // Preview-only — how to render the demo card
  previewBg: string;
};

export const TEMPLATES: SubtitleTemplate[] = [
  {
    id: "plain",
    name: "פשוט",
    description: "צבע אחיד, בלי הדגשת מילה. הסגנון המקורי",
    category: "clean",
    previewBg: "from-zinc-700 to-zinc-900",
    style: {
      fontFamily: "Heebo",
      fontSize: 48,
      fontWeight: 700,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 3,
      backgroundColor: "#000000",
      backgroundOpacity: 0,
      position: "bottom",
      positionOffset: 100,
      textAlign: "center",
      highlightColor: "#FFFFFF",
      shadow: true,
    },
  },
  {
    id: "hormozi",
    name: "Hormozi",
    description: "צהוב גדול ועוצמתי — לטיקטוק ויראלי",
    category: "viral",
    previewBg: "from-yellow-400 to-orange-500",
    style: {
      fontFamily: "Rubik",
      fontSize: 78,
      fontWeight: 900,
      color: "#FACC15",
      strokeColor: "#000000",
      strokeWidth: 8,
      backgroundColor: "#000000",
      backgroundOpacity: 0,
      position: "middle",
      positionOffset: 0,
      textAlign: "center",
      highlightColor: "#22C55E",
      shadow: true,
    },
  },
  {
    id: "beast",
    name: "Beast",
    description: "לבן עם רקע ירוק — סגנון MrBeast",
    category: "viral",
    previewBg: "from-green-400 to-emerald-600",
    style: {
      fontFamily: "Rubik",
      fontSize: 70,
      fontWeight: 900,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 6,
      backgroundColor: "#10B981",
      backgroundOpacity: 1,
      position: "middle",
      positionOffset: 0,
      textAlign: "center",
      highlightColor: "#FACC15",
      shadow: true,
    },
  },
  {
    id: "karaoke",
    name: "Karaoke",
    description: "כל מילה נצבעת ברגע שנאמרת",
    category: "fun",
    previewBg: "from-pink-500 to-purple-600",
    style: {
      fontFamily: "Heebo",
      fontSize: 64,
      fontWeight: 800,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 5,
      backgroundColor: "#000000",
      backgroundOpacity: 0,
      position: "bottom",
      positionOffset: 150,
      textAlign: "center",
      highlightColor: "#EC4899",
      shadow: true,
    },
  },
  {
    id: "neon",
    name: "Neon",
    description: "ניאון זוהר — סייברפאנק",
    category: "fun",
    previewBg: "from-cyan-400 via-purple-500 to-pink-500",
    style: {
      fontFamily: "Rubik",
      fontSize: 60,
      fontWeight: 800,
      color: "#06B6D4",
      strokeColor: "#581C87",
      strokeWidth: 3,
      backgroundColor: "#000000",
      backgroundOpacity: 0,
      position: "bottom",
      positionOffset: 120,
      textAlign: "center",
      highlightColor: "#F472B6",
      shadow: true,
    },
  },
  {
    id: "ali",
    name: "Ali",
    description: "פשוט ונקי — סגנון Ali Abdaal",
    category: "clean",
    previewBg: "from-slate-600 to-slate-800",
    style: {
      fontFamily: "Assistant",
      fontSize: 44,
      fontWeight: 700,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 2,
      backgroundColor: "#000000",
      backgroundOpacity: 0.75,
      position: "bottom",
      positionOffset: 90,
      textAlign: "center",
      highlightColor: "#FACC15",
      shadow: false,
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "לבן נקי, בלי רקע. סגנון פודקאסט",
    category: "clean",
    previewBg: "from-gray-200 to-gray-400",
    style: {
      fontFamily: "Heebo",
      fontSize: 40,
      fontWeight: 600,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 1,
      backgroundColor: "#000000",
      backgroundOpacity: 0,
      position: "bottom",
      positionOffset: 100,
      textAlign: "center",
      highlightColor: "#FACC15",
      shadow: true,
    },
  },
  {
    id: "bold-pop",
    name: "Bold Pop",
    description: "ורוד צהוב — צבעוני ושמח",
    category: "fun",
    previewBg: "from-fuchsia-500 to-yellow-400",
    style: {
      fontFamily: "Rubik",
      fontSize: 68,
      fontWeight: 900,
      color: "#FFFFFF",
      strokeColor: "#EC4899",
      strokeWidth: 7,
      backgroundColor: "#000000",
      backgroundOpacity: 0,
      position: "middle",
      positionOffset: 50,
      textAlign: "center",
      highlightColor: "#FACC15",
      shadow: true,
    },
  },
  {
    id: "elegant",
    name: "Elegant",
    description: "אלגנטי לחתונות ולתוכן מסחרי",
    category: "elegant",
    previewBg: "from-amber-200 to-yellow-600",
    style: {
      fontFamily: "Bellefair",
      fontSize: 38,
      fontWeight: 400,
      color: "#FEF3C7",
      strokeColor: "#451A03",
      strokeWidth: 1,
      backgroundColor: "#000000",
      backgroundOpacity: 0.4,
      position: "bottom",
      positionOffset: 110,
      textAlign: "center",
      highlightColor: "#FACC15",
      shadow: true,
    },
  },
  {
    id: "tiktok",
    name: "TikTok",
    description: "לבן עם שחור עבה — קלאסיקה",
    category: "viral",
    previewBg: "from-pink-400 via-rose-500 to-red-500",
    style: {
      fontFamily: "Rubik",
      fontSize: 58,
      fontWeight: 800,
      color: "#FFFFFF",
      strokeColor: "#000000",
      strokeWidth: 5,
      backgroundColor: "#000000",
      backgroundOpacity: 0,
      position: "middle",
      positionOffset: 0,
      textAlign: "center",
      highlightColor: "#F472B6",
      shadow: true,
    },
  },
  {
    id: "instagram",
    name: "Instagram",
    description: "גרדיאנט סגול-ורוד מודרני",
    category: "fun",
    previewBg: "from-orange-400 via-pink-500 to-purple-600",
    style: {
      fontFamily: "Heebo",
      fontSize: 54,
      fontWeight: 800,
      color: "#FFFFFF",
      strokeColor: "#7C3AED",
      strokeWidth: 4,
      backgroundColor: "#7C3AED",
      backgroundOpacity: 0.4,
      position: "bottom",
      positionOffset: 130,
      textAlign: "center",
      highlightColor: "#FCD34D",
      shadow: true,
    },
  },
];
